---
# VM's which deployed by generic-x64/ubuntu2204 has preset 12h time format. This playbook set 24h format
- name: Set LC_TIME
  hosts: all
  become: yes
  tasks:
    - name: Set 24h time format
      ansible.builtin.command: "localectl set-locale LC_TIME='en_GB.UTF-8'"
