---
namespaces: ['argocd', 'infra', 'monitoring', 'cert-manager']

applications:
  - name: argocd
    namespace: argocd
    chart: argo-cd
    targetRevision: 6.6.0
    repoURL: https://argoproj.github.io/argo-helm
  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager
    targetRevision: v1.14.3
    repoURL: https://charts.jetstack.io
  - name: istiod
    namespace: istio-system
    chart: istiod
    targetRevision: 1.20.3
    repoURL: https://istio-release.storage.googleapis.com/charts
  - name: istio-ingressgateway
    namespace: istio-system
    chart: gateway
    targetRevision: 1.20.3
    repoURL: https://istio-release.storage.googleapis.com/charts
  - name: istio-base
    namespace: istio-system
    chart: base
    targetRevision: 1.20.3
    repoURL: https://istio-release.storage.googleapis.com/charts
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        jsonPointers:
          - /webhooks/0/failurePolicy

extraManifests:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: primary
      namespace: metallb-system
    spec:
      addresses:
        - 192.168.121.248/30
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: primary
      namespace: metallb-system
    spec:
      ipAddressPools:
        - primary
  - apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: self-signed
      namespace: cert-manager
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      selfSigned: { }
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: home.lab
      namespace: istio-system
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      duration: 86400h0m0s
      renewBefore: 12h0m0s
      commonName: "*.home.lab"
      dnsNames:
        - "*.home.lab"
      secretName: home.lab
      isCA: true
      issuerRef:
        name: self-signed
        kind: ClusterIssuer
  - apiVersion: networking.istio.io/v1beta1
    kind: Gateway
    metadata:
      name: main
      namespace: istio-system
    spec:
      selector:
        istio: ingressgateway
      servers:
        - hosts:
            - '*'
          port:
            name: http
            number: 80
            protocol: HTTP2
        - hosts:
            - '*'
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            credentialName: home.lab
            mode: SIMPLE
  - apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      name: argocd-http
      namespace: argocd
    spec:
      gateways:
        - istio-system/main
      hosts:
        - argocd.home.lab
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: argocd-server
                port:
                  number: 80
