---
container_manager: crio
kube_proxy_strict_arp: true

# Kube VIP
kube_vip_enabled: true
kube_vip_arp_enabled: true
kube_vip_controlplane_enabled: true
kube_vip_address: 192.168.121.100
loadbalancer_apiserver:
  address: "{{ kube_vip_address }}"
  port: 6443
kube_vip_services_enabled: true
kube_vip_enableServicesElection: true
kubeconfig_localhost: true
