---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home.lab
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  duration: 86400h0m0s
  renewBefore: 12h0m0s
  commonName: "*.home.lab"
  dnsNames:
    - "*.home.lab"
  secretName: home.lab
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
